# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIdKpL5ejHBuWE_Ia3xGFoMJvc7ldkci
"""

!pip install numpy pandas

import numpy as np
import pandas as pd

movies= pd.read_csv('tmdb_5000_movies.csv')
credits= pd.read_csv('tmdb_5000_credits.csv')

movies.head(1)

credits.head(1)

#merge these 2 datasets on the basis of id or name

movies= movies.merge(credits, on= 'title')#columns combined

movies.head(1)

#removing unnecessary columns - which wouldnt be used for recommendation like budget, homepage

#imp cols- genres id keywords title overview cast crew

movies= movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

#remove columns w missing values
movies.isnull().sum()

movies.dropna(inplace= True)

movies.duplicated().sum()

# reformat the columns

movies.iloc[0].genres

#need above in this format- ['action', 'adventure', 'fantasy', 'scifi']

import json

def convert(obj):
    # if obj is a string, convert it to Python list
    if isinstance(obj, str):
        obj = json.loads(obj)
    return [i['name'] for i in obj]

movies['genres'] = movies['genres'].apply(convert)

movies.iloc[0].genres

movies.head() #genres theek hogya

movies['keywords'] = movies['keywords'].apply(convert)

movies.head()

#we need top 3 characters from cast

import ast  # for safely evaluating the string

def convert3(text):
    L = []
    counter = 0
    # convert string to list of dicts
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

# Apply the function
movies['cast'] = movies['cast'].apply(convert3)

# Check the result
movies.head()

import ast

def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

movies['crew'] = movies['crew'].apply(fetch_director)

movies.head()

#convert "overview" string into a list
movies['overview']= movies['overview'].apply(lambda x: x.split())

#before concatenating all columns into 1 single column of tags, we need to remove spaces: Sam Worthington -> SamWorthington
#Sam Mendes -> SamMendes

movies['genres']= movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])  #science fiction -> sciencefiction

movies['keywords']= movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['cast']= movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['crew']= movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

movies.head()

#NOW FINALLY WE CAN CONCATINATE THESE COLUMNS INTO 1 NEW COLUMN CALLED "TAGS"
movies['tags']= movies['overview'] + movies['genres'] + movies ['keywords'] + movies['cast'] + movies['crew']

movies.head()

#remove rest columns - make a new df
new_df= movies[['movie_id', 'title', 'tags']]

new_df.head()

#convert list into string
new_df['tags']= new_df['tags'].apply (lambda x: " ". join(x))

new_df['tags'][0]

#convert into lowerase
new_df['tags']= new_df['tags'].apply(lambda x:x.lower())

new_df.head()

#NOW WE DO TEXT VECTORIZATION USING BoW
#we wouldnt be considering stopwords (a, is, the...)

#can be done easlity using scikitlearn library

!pip install scikit-learn

from sklearn.feature_extraction.text import CountVectorizer
#make a class
cv= CountVectorizer(max_features= 5000, stop_words='english')

vectors= cv.fit_transform(new_df['tags']).toarray() #convert into array to reduce sparse 0 values

cv.get_feature_names_out()

#stemming (similar words): ['loved', 'loving', 'love'] -> ['love', 'love', 'love']

!pip install nltk

import nltk

from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

def stem(text):
  y= []
  for i in text.split():
    y.append(ps.stem(i))

  return " ". join(y)

new_df['tags']= new_df['tags'].apply(stem)

from sklearn.feature_extraction.text import CountVectorizer
#make a class
cv= CountVectorizer(max_features= 5000, stop_words='english')
vectors= cv.fit_transform(new_df['tags']).toarray() #convert into array to reduce sparse 0 values
cv.get_feature_names_out()

#VECTORS OF EACH MOVIE HAVE BEEN MADE
#NOW WE WISH TO CALCULATE DISTANCE OF EACH MOVIE FROM THE OTHER MOVIE
# DIST MORE SIMILARITY LESS

#WE DONT CALCULATE EUCLIDIAN DISTANCE -> INSTEAD WE WILL CALCULATE THE COSINE DISTANCE (ANGLES)
# EUCLIDIAN DISTANCE FAILS WHEN WE'VE HIGH DIMENSIONAL DATA

#cosine similarity function in skicit learn
from sklearn.metrics.pairwise import cosine_similarity

similarity= cosine_similarity(vectors)

similarity[0]  #1st movie ka baaki movies ke sath similarity score => 1st ka 1st ke sath score 1 hoga

sorted(list(enumerate(similarity[0])), reverse= True, key= lambda x: x[1]) [1:6]

def recommend(movie):
  #fetch index
  movie_index= new_df[new_df['title']== movie]. index[0]
  distances= similarity[movie_index]
  #sort similarity distances
  #zada similarity score means zada similar
  movies_list=   sorted(list(enumerate(distances)), reverse= True, key= lambda x: x[1]) [1:6]

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

recommend('Avatar')